#!/usr/bin/env bash
# display information about domain and sub-domains which points to an address


display_function ()
{
    domain="$1"
    if [ "$2" ]
    then
	subdomain="$2"
    else
	subdomain="www lb-01 web-01 web-02"
    fi
    for sub in $subdomain
    do
	echo -n "The subdomain $sub"
	dig $sub.$domain | grep -A1 'ANSWER SECTION:' | tail -n 1 | awk '{print " is a " $4 " record and points to " $5}'
    done
}

display_function "$1" "$2"
