#!/usr/bin/env bash
# A Bash script that transfers a file from our client to a server

if [ "$#" -le 3 ]; then
echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
exit
fi

scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no "$1" -i "$4" "$3"@"$2":~/
