#!/usr/bin/env bash
# a Bash script that configures a client machine to install nginx

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw -f enable
sudo ufw allow 'Nginx HTTP'
sudo service nginx start
echo 'Hello World!' | sudo tee /usr/share/nginx/html/index.html
sudo service restart nginx


# The tee command, used with a pipe, reads standard input, then writes the output of a program to stand# ard output and simultaneously copies it into the specified file or files. Use the tee command to view# your output immediately and at the same time, store it for future use.