#!/usr/bin/env bash
# a Bash script that configures a client machine to install nginx

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw enable
sudo ufw allow 'Nginx HTTP'
echo 'Hello World!' | sudo tee var/www/html.index.nginx-debian.html

# The tee command, used with a pipe, reads standard input, then writes the output of a program to stand# ard output and simultaneously copies it into the specified file or files. Use the tee command to view# your output immediately and at the same time, store it for future use.

sudo service restart nginx