#!/usr/bin/env bash
# a Bash script that configures a client machine to install nginx

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw -f enable
sudo ufw allow 'Nginx HTTP'
echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx start
