#!/usr/bin/env bash
# a Bash script that containing commands to automatically redirect pages in nginx

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw -f enable
sudo ufw allow 'Nginx HTTP'
sudo ufw allow 22
echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html
sudo chmod 777 /etc/nginx/sites-available/default
sudo sed -i "s/server_name _;/server_name qutebunnos.tech;\n\trewrite ^\/redirect_me https:\/\/youtube.com permanent;/" /etc/nginx/sites-available/default
sudo service restart nginx
