#!/usr/bin/env bash
# Script to redirect 404 page

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw --force enable
sudo ufw allow 'Nginx HTTP'
echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html
sudo chmod 777 /etc/nginx/sites-available/default
sudo sed -i "s/server_name _;/server_name roadsidedev.tech;\n\trewrite ^\/redirect_me https:\/\/youtube.com permanent;/" /etc/nginx/sites-available/default
sudo touch /var/www/html/error404.html
sudo chmod 777 /var/www/html/error404.html
echo "Ceci n'est pas une page" > /var/www/html/error404.html
sudo sed -i "s/root \/var\/www\/html;/root \/var\/www\/html;\n\n\terror_page 404 \/error404.html;/" /etc/nginx/sites-available/default
sudo service nginx restart