#!/usr/bin/env bash
# Install haproxy and configure the load balancer


sudo apt-get -y update
sudo apt-get -y install haproxy
sudo chmod 777 /etc/haproxy/haproxy.cfg
echo '
frontend http_front
	 bind *:80
	 stats uri /haproxy?stats
	 default_backend http_back
backend http_back
	balance roundrobin
	server 1738-web-01 34.75.181.236:80 check
	server 1738-web-02 34.73.98.236:80 check' >> /etc/haproxy/haproxy.cfg
sudo chmod 777 /etc/default/haproxy
echo 'ENABLED=1' >> /etc/default/haproxy
sudo service haproxy restart
