#!/usr/bin/env bash
# Install haproxy and configure the load balancer


sudo apt-get -y update
sudo apt-get -y install haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
sudo sed -i "\$ a\listen appname\n\tbind 0.0.0.0:80\n\tmode http\n\tstats enable\n\tbalance roundrobin\n\toption httpclose\n\toption forwardfor\n\tserver 1738-web-01 3.238.73.69:80 check\n\tserver 1738-web-02 3.226.244.239:80 check" /etc/haproxy/haproxy.cfg
sudo service haproxy start