#!/usr/bin/env bash
# MySQL backup script

file_date=$(date +"%d-%m-%y")
extension='.tar.gz'
file_name="$file_date$extension"
mysqldump --opt --user='root' --password="$1" --all-databases > backup.sql > /dev/null 2>&1
tar -czvf ${file_name} backup.sql > /dev/null 2>&1