#!/usr/bin/env bash
# This script pings an IP address passed as an argument.

# Requirements:

# Accepts a string as an argument
# Displays Usage: 5-is_the_host_on_the_network {IP_ADDRESS} if no argument passed
# Ping the IP 5 times


if [ $# -gt 0 ]; then
    ping "$1" -c 5
elif [ $# -eq 0 ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
 fi
