#!/usr/bin/env bash
# This a Bash script that loops from 1 to 10 and:

# displays bad luck for the 4th loop iteration
# displays good luck for the 8th loop iteration
# displays Best School for the other iterations

I=1
LIMIT=11

while((I < LIMIT))
do
if [ $I -eq 4 ]; then
echo "bad luck"
elif [ $I -eq 8 ]; then
echo "good luck"
else
echo "Best School"
fi
((I++))
done
