#!/usr/bin/env bash
# This script that displays the time for 12 hours and 59 minutes:

# display hours from 0 to 12
# display minutes from 1 to 59

HOURS=0

while((HOURS < 13))
do
    echo "Hour:" "$HOURS"
    MINUTES=1
while((MINUTES < 60))
do
echo "$MINUTES"
((MINUTES++))
done
((HOURS++))
done
